name 'mail_handler'
maintainer 'ChrisD13'
maintainer_email 'chris.duong83@gmail.com'
license 'mit'
description 'Installs/Configures mail_handler'
long_description 'Installs/Configures mail_handler'
version '0.1.0'

depends 'chef-client'
depends 'chef_handler'
